### ISSUE TITLE
.net standard support based on NPOI

### ISSUE THREAD

**Issue by tonyqus** [nabehiro/TableIO#6]
Since NPOI 2.4.1 has provided support for .NET standard 2.0, I suggest you can consider switching from ClosedXml to NPOI for .net core version. I can provide technical support for NPOI if you want.

**Comment by nabehiro** [comment]
Thanks for your suggestion.
Now, TableIO.NPOI has support .NET standard 2.0 !

https://www.nuget.org/packages/TableIO.NPOI/
